---
title: "Group Project One"
author: "Daniel Serna and Laura Niederlander"
date: "September 16, 2018"
output: html_document
---

```{r installPackages}
if(!require(tidyverse)) install.packages("tidyverse")
if(!require(sqldf)) install.packages("sqldf")
if(!require(glmnet)) install.packages("glmnet")
if(!require(randomForest)) install.packages("randomForest")
```
```{r importData}
trainData <- read.csv("train.csv")
head(trainData)
```

```{r addUtilityFunctions}
panel.hist <- function(x, ...)
{
    usr <- par("usr"); on.exit(par(usr))
    par(usr = c(usr[1:2], 0, 1.5) )
    h <- hist(x, plot = FALSE)
    breaks <- h$breaks; nB <- length(breaks)
    y <- h$counts; y <- y/max(y)
    rect(breaks[-nB], 0, breaks[-1], y, col = "cyan", ...)
}
```

```{r removeOutliers}
trainDataCleaned <- trainData
trainDataCleaned <- trainDataCleaned[which(trainDataCleaned$build_year >= 1691 | is.na(trainDataCleaned$build_year)),]
trainDataCleaned <- trainDataCleaned[which(trainDataCleaned$build_year <= 2018 | is.na(trainDataCleaned$build_year)),]
trainDataCleaned <- trainDataCleaned[which(trainDataCleaned$full_sq <= 5000)| is.na(trainDataCleaned$full_sq),]
trainDataCleaned <- trainDataCleaned[which(trainDataCleaned$kitch_sq <= 1500| is.na(trainDataCleaned$kitch_sq)),]
trainDataCleaned <- trainDataCleaned[which(trainDataCleaned$life_sq <= 1000| is.na(trainDataCleaned$life_sq)),]
trainDataCleaned <- trainDataCleaned[which(trainDataCleaned$state <= 4| is.na(trainDataCleaned$state)),]
trainDataCleaned <- trainDataCleaned[which(trainDataCleaned$kitch_sq < 600| is.na(trainDataCleaned$kitch_sq)),]
trainDataCleaned <- trainDataCleaned[which(trainDataCleaned$floor > 0| is.na(trainDataCleaned$floor)),]
trainDataCleaned <- trainDataCleaned[which(trainDataCleaned$num_room > 0 | is.na(trainDataCleaned$num_room)),]
trainDataCleaned <- trainDataCleaned[which(trainDataCleaned$max_floor > 0| is.na(trainDataCleaned$max_floor)),]
```

```{r dataCleanup}

#convert yes/no values to 1/0
trainDataCleaned$culture_objects_top_25 <- ifelse(trainDataCleaned$culture_objects_top_25 =="yes", 1, 0)
trainDataCleaned$full_all <- ifelse(trainDataCleaned$full_all =="yes", 1, 0)
trainDataCleaned$incineration_raion <- ifelse(trainDataCleaned$incineration_raion =="yes", 1, 0)
trainDataCleaned$oil_chemistry_raion <- ifelse(trainDataCleaned$oil_chemistry_raion =="yes", 1, 0)
trainDataCleaned$radiation_raion <- ifelse(trainDataCleaned$radiation_raion =="yes", 1, 0)
trainDataCleaned$railroad_terminal_raion <- ifelse(trainDataCleaned$railroad_terminal_raion =="yes", 1, 0)
trainDataCleaned$big_market_raion <- ifelse(trainDataCleaned$big_market_raion =="yes", 1, 0)
trainDataCleaned$nuclear_reactor_raion <- ifelse(trainDataCleaned$nuclear_reactor_raion =="yes", 1, 0)
trainDataCleaned$detention_facility_raion <- ifelse(trainDataCleaned$detention_facility_raion =="yes", 1, 0)
trainDataCleaned$thermal_power_plant_raion <- ifelse(trainDataCleaned$thermal_power_plant_raion =="yes", 1, 0)
trainDataCleaned$water_1line <- ifelse(trainDataCleaned$water_1line =="yes", 1, 0)
trainDataCleaned$big_road1_1line <- ifelse(trainDataCleaned$big_road1_1line =="yes", 1, 0)
trainDataCleaned$railroad_1line <- ifelse(trainDataCleaned$railroad_1line =="yes", 1, 0)


#convert product_type NAs to Investment
trainDataCleaned[is.na(trainDataCleaned[,which(names(trainDataCleaned) == "product_type")]), which(names(trainDataCleaned) == "product_type")] <- "Investment"

#convert sub_area NAs to Ajeroport
trainDataCleaned[is.na(trainDataCleaned[,which(names(trainDataCleaned) == "sub_area")]), which(names(trainDataCleaned) == "sub_area")] <- "Ajeroport"

#exclude not numeric columns for NA cleanup.
columnsToExclude <- names(trainDataCleaned) %in% c("timestamp", "product_type", "sub_area", "ecology") 
subsetCleaned <- trainDataCleaned[!columnsToExclude]

#apply column mean to NA values 
for(i in 1:ncol(subsetCleaned)){
  subsetCleaned[is.na(subsetCleaned[,i]), i] <- mean(subsetCleaned[,i], na.rm = TRUE)
}

#add non numeric columns back in.
subsetCleaned$timestamp <- trainDataCleaned$timestamp
subsetCleaned$product_type <- trainDataCleaned$product_type
subsetCleaned$sub_area <- trainDataCleaned$sub_area
subsetCleaned$ecology <- trainDataCleaned$ecology
```

```{r dataAnalysis1}
pairs(~price_doc+full_sq+life_sq+floor+max_floor+material+build_year+num_room+kitch_sq+state,data=subsetCleaned, 
   main="Simple Scatterplot Matrix", diag.panel=panel.hist)
```

```{r logTransform}
subsetCleanedLogged <- subsetCleaned
subsetCleanedLogged$log_price_doc = log(subsetCleanedLogged$price_doc) 
subsetCleanedLogged$log_full_sq = log(subsetCleanedLogged$full_sq)
subsetCleanedLogged$log_life_sq = log(subsetCleanedLogged$life_sq)
subsetCleanedLogged$log_floor = log(subsetCleanedLogged$floor)
subsetCleanedLogged$log_max_floor = log(subsetCleanedLogged$max_floor)
subsetCleanedLogged$log_material = log(subsetCleanedLogged$material)
subsetCleanedLogged$log_num_room = log(subsetCleanedLogged$num_room)
subsetCleanedLogged$log_kitch_sq = log(subsetCleanedLogged$kitch_sq)
subsetCleanedLogged$log_state = log(subsetCleanedLogged$state)
```



```{r dataAnalysisLogTransformed}
pairs(~log_price_doc+log_full_sq+log_life_sq+log_floor+log_max_floor+log_material+log_num_room+log_kitch_sq+log_state,data=subsetCleanedLogged, 
   main="Simple Scatterplot Matrix", diag.panel=panel.hist)
```

```{r LASSOAnalyiss}
log_price_doc_columnIndex <- which(names(subsetCleanedLogged)=="log_price_doc")
x <- as.matrix(subsetCleanedLogged[,-log_price_doc_columnIndex]) # Removes class
y <- as.double(as.matrix(subsetCleanedLogged[, log_price_doc_columnIndex])) # Only class

# Fitting the model (Lasso: Alpha = 1)
set.seed(999)
cv.lasso <- cv.glmnet(x, y, family='binomial', alpha=1, parallel=TRUE, standardize=TRUE, type.measure='auc')

# Results
plot(cv.lasso)
plot(cv.lasso$glmnet.fit, xvar="lambda", label=TRUE)
cv.lasso$lambda.min
cv.lasso$lambda.1se
coef(cv.lasso, s=cv.lasso$lambda.min)
```

```{r randomForest}
predictors <- (subsetCleanedLogged[,-log_price_doc_columnIndex]) # Removes class
response <- (as.matrix(subsetCleanedLogged[, log_price_doc_columnIndex])) # Only class
fit <- randomForest(x = predictors, y=response,
                      data=subsetCleanedLogged, 
                      importance=TRUE, 
                      ntree=2000)
```

```{r least angle regression}

library(lars)

lasso <- lars(x=as.matrix(subsetCleaned$full_sq,subsetCleaned$life_sq,subsetCleaned$floor,subsetCleaned$max_floor,subsetCleaned$material,subsetCleaned$build_year,subsetCleaned$num_room,subsetCleaned$kitch_sq,subsetCleaned$state,subsetCleaned$product_type,subsetCleaned$sub_area,subsetCleaned$area_m,subsetCleaned$raion_popul,subsetCleaned$green_zone_part,subsetCleaned$indust_part,subsetCleaned$children_preschool), y=subsetCleanedLogged$log_price_doc, type = "lar",  trace = FALSE, normalize = TRUE)

plot(lasso)


```




```{r randomforest sample}


data(iris)
set.seed(111)
ind <- sample(2, nrow(iris), replace = TRUE, prob=c(0.8, 0.2))
iris.rf <- randomForest(Species ~ ., data=iris[ind == 1,])
iris.pred <- predict(iris.rf, iris[ind == 2,])
table(observed = iris[ind==2, "Species"], predicted = iris.pred)
## Get prediction for all trees.
predict(iris.rf, iris[ind == 2,], predict.all=TRUE)
## Proximities.
predict(iris.rf, iris[ind == 2,], proximity=TRUE)
## Nodes matrix.
str(attr(predict(iris.rf, iris[ind == 2,], nodes=TRUE), "nodes"))

```



